### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by fourjr** [cgrok/clashroyale#1]
docs in readme that links to api docs + basic instructions on sync/async

@kyb3r opinions

**Comment by SharpBit** [comment]
well tnt and sleedyak are supposed to do it but none of them started and @freetnt5852 doesn't have a clue, as usual

**Comment by AmirSavand** [comment]
The necessary docs are in the cr-api itself, checking out the examples directory in here is enough.

```python
# Access API data via snake_case instead of camelCase
# Everything is exactly the same as what is 
# presented in the official API documentation
```

**Comment by fourjr** [comment]
Pretty sure camelCase would work as well.

**Comment by fourjr** [comment]
To get a list of methods, you can run `dir(clashroyale.Client)`
