### ISSUE TITLE
requirements.txt and setup.py list different package version numbers

### ISSUE THREAD

**Issue by jykntr** [cgrok/clashroyale#12]
`aiohttp` and `python-box` have different versions listed in `setup.py` & `requirements.txt`.  I believe `requirements.txt` Is correct.

https://github.com/cgrok/clashroyale/blob/20f64893342b19d8aeaaa2e31ead1b71d617ae88/setup.py#L17
https://github.com/cgrok/clashroyale/blob/20f64893342b19d8aeaaa2e31ead1b71d617ae88/requirements.txt#L1-L2

**Comment by fourjr** [comment]
Will change soon, you can help by doing a PR
