### ISSUE TITLE
Equality Tests?

### ISSUE THREAD

**Issue by kyb3r** [cgrok/clashroyale#2]
Should we put equality tests for models?

```py
player1 = client.get_profile('2CCP')
player2 = client.get_profile('2CCP')
assert player1 == player2
```

Should we test by tag or if the data is the exact same?

**Comment by fourjr** [comment]
Added tests to compare by tag with blocking client in https://github.com/cgrok/clashroyale/commit/9796e5d7ae0fa090221355e590f564f6a6ec9a6b
