### ISSUE TITLE
Error in Field Filtering

### ISSUE THREAD

**Issue by ManinderAngural** [cgrok/clashroyale#23]
The error occurs in the `get_player(*tags: crtag, **params: keys)` method which fails to filter specified fields.

**Here's the code**
```python    
@commands.cooldown(2,5,commands.BucketType.user)
@commands.command(name="test")
    async def _test(self, ctx, *, tag=None):
        async with ctx.typing():
            if tag is None:
                return
            try:
                player = await self.client.get_player(tag, keys = ["name","trophies"])
            except ValueError as f:
                return await ctx.send(f)
            else:
                print(player)
```

### Expected Result
The player object with the filtered fields, name and trophies.

### Actual Result 
The player object with all the stats in it.

**Comment by fourjr** [comment]
API Issue, [RoyaleAPI/cr-api#395](https://github.com/RoyaleAPI/cr-api/issues/395)
